version: '3.8'

services:
  react-dev:
    build:
      context: ../..
      dockerfile: docker/dev/Dockerfile.dev
    container_name: next-move-react-dev
    ports:
      - "3000:3000"
    volumes:
      - ../..:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_HOST=0.0.0.0
    stdin_open: true
    tty: true